### PR TITLE
Remove datasets zip files from the repo and modify READMEs

### PR DESCRIPTION
**Pull request by mayaCostantini**
## Related Issues and Dependencies

Related to #31 

## This introduces a breaking change

- [ ] Yes
- [x] No

## This Pull Request implements

Remove all zip files of datasets that were moved to the operate first public bucket after backing them up locally and remove mentions of those files from the READMEs.

### CODE REVIEW

**Review by pacospace — COMMENTED** [review]
lgtm!! Just one small comment: we need to remove also the .gitattribute files from the root and from the datasets repo (I think it is in solver repo at least).

Otherwise nice work!! 💯

**Comment by mayaCostantini** [comment]
Thanks @pacospace , it's done!

**Review by pacospace — APPROVED** [review]
👏🏼 Thanks!

**Pull request merged**
