### PR TITLE
Links of solver and invectio

### PR DESCRIPTION
**Pull request by tlegen-k**
## Related Issues and Dependencies
thoth-station/invectio#99
…

## This introduces a breaking change

- [ ] Yes
- [x] No

## This Pull Request implements

Add jupyter notebook to analyze links of solver reports and invectio output.

### CODE REVIEW

**Comment by tlegen-k** [comment]
Hi @fridex 
Will you be able to take a look on the links of solver report and invectio output, and on the proposed solution of correctly identifying package names?

**Comment by fridex** [comment]
> Will you be able to take a look on the links of solver report and invectio output, and on the proposed solution of correctly identifying package names?

Had a brief look here - not sure if I understand the proposed solution correctly. Do you want to match package names based on `Download-URL` field in metadata?

**Comment by tlegen-k** [comment]
Idea is:
- in invectio write function similar to `get_source_repos()` from [app.py](https://github.com/thoth-station/solver-project-url-job/blob/master/app.py) at [solver-project-url](https://github.com/thoth-station/solver-project-url-job) repo that can access the solver reports output
-  to find and compare the name of module from `tree['packages']'`field with data from `tree['importlib_metadata']['metadata']['Name']`. As latter has the name as it appears on pypi.org.
- use the derived name in our output /or/ create database with all the nonmatching package names that we know

**Comment by tlegen-k** [comment]
> > Will you be able to take a look on the links of solver report and invectio output, and on the proposed solution of correctly identifying package names?
> 
> Had a brief look here - not sure if I understand the proposed solution correctly. Do you want to match package names based on `Download-URL` field in metadata?

Thanks for looking at it.

Idea is:
- in invectio write function similar to `get_source_repos()` from [app.py](https://github.com/thoth-station/solver-project-url-job/blob/master/app.py) at [solver-project-url](https://github.com/thoth-station/solver-project-url-job) repo that can access the solver reports output
-  to find and compare the name of module from `tree['packages']'`field with data from `tree['importlib_metadata']['metadata']['Name']`. As latter has the name as it appears on pypi.org.

**Comment by fridex** [comment]
> > > Will you be able to take a look on the links of solver report and invectio output, and on the proposed solution of correctly identifying package names?
> > 
> > 
> > Had a brief look here - not sure if I understand the proposed solution correctly. Do you want to match package names based on `Download-URL` field in metadata?
> 
> Thanks for looking at it.
> 
> Idea is:
> 
> * in invectio write function similar to `get_source_repos()` from [app.py](https://github.com/thoth-station/solver-project-url-job/blob/master/app.py) at [solver-project-url](https://github.com/thoth-station/solver-project-url-job) repo that can access the solver reports output
> * to find and compare the name of module from `tree['packages']'`field with data from `tree['importlib_metadata']['metadata']['Name']`. As latter has the name as it appears on pypi.org.

I'm not sure if invectio should access solver documents. The original idea was to create a database entry that would hold packages available for the given python package release (the `tree[0]["packages"]` field) and create an API endpoint that would try to match these packages with the ones stored in the database.

So in other words, extend [syncing of solver documents](https://github.com/thoth-station/storages/blob/aba29808b2acb062bee1f2ac3b379eb7930c4398/thoth/storages/graph/postgres.py#L5262) in a way they store also information about packages that are available.

**Comment by pacospace** [comment]
> > > > Will you be able to take a look on the links of solver report and invectio output, and on the proposed solution of correctly identifying package names?
> > > 
> > > 
> > > Had a brief look here - not sure if I understand the proposed solution correctly. Do you want to match package names based on `Download-URL` field in metadata?
> > 
> > 
> > Thanks for looking at it.
> > Idea is:
> > 
> > * in invectio write function similar to `get_source_repos()` from [app.py](https://github.com/thoth-station/solver-project-url-job/blob/master/app.py) at [solver-project-url](https://github.com/thoth-station/solver-project-url-job) repo that can access the solver reports output
> > * to find and compare the name of module from `tree['packages']'`field with data from `tree['importlib_metadata']['metadata']['Name']`. As latter has the name as it appears on pypi.org.
> 
> I'm not sure if invectio should access solver documents. The original idea was to create a database entry that would hold packages available for the given python package release (the `tree[0]["packages"]` field) and create an API endpoint that would try to match these packages with the ones stored in the database.
> 
> So in other words, extend [syncing of solver documents](https://github.com/thoth-station/storages/blob/aba29808b2acb062bee1f2ac3b379eb7930c4398/thoth/storages/graph/postgres.py#L5262) in a way they store also information about packages that are available.

Yes @tlegen-k, agree with @fridex! So let's:

- create alembic migration for the new entry where we want to sync `tree[0]["packages"]`
- extend sync logic of solver in thoth-storages
- expose that in User-API endpoint
- extend invectio report result to consider user-api endpoint and make results more robust? So we can use them in jupyterlab-requirements to discover Pipfile from notebook without dependencies and kebechet manager (https://github.com/thoth-station/kebechet/issues/727)?

**Comment by tlegen-k** [comment]
> > > > > Will you be able to take a look on the links of solver report and invectio output, and on the proposed solution of correctly identifying package names?
> > > > 
> > > > 
> > > > Had a brief look here - not sure if I understand the proposed solution correctly. Do you want to match package names based on `Download-URL` field in metadata?
> > > 
> > > 
> > > Thanks for looking at it.
> > > Idea is:
> > > 
> > > * in invectio write function similar to `get_source_repos()` from [app.py](https://github.com/thoth-station/solver-project-url-job/blob/master/app.py) at [solver-project-url](https://github.com/thoth-station/solver-project-url-job) repo that can access the solver reports output
> > > * to find and compare the name of module from `tree['packages']'`field with data from `tree['importlib_metadata']['metadata']['Name']`. As latter has the name as it appears on pypi.org.
> > 
> > 
> > I'm not sure if invectio should access solver documents. The original idea was to create a database entry that would hold packages available for the given python package release (the `tree[0]["packages"]` field) and create an API endpoint that would try to match these packages with the ones stored in the database.
> > So in other words, extend [syncing of solver documents](https://github.com/thoth-station/storages/blob/aba29808b2acb062bee1f2ac3b379eb7930c4398/thoth/storages/graph/postgres.py#L5262) in a way they store also information about packages that are available.
> 
> Yes @tlegen-k, agree with @fridex! So let's:
> 
>     * create alembic migration for the new entry where we want to sync `tree[0]["packages"]`
> 
>     * extend sync logic of solver in thoth-storages
> 
>     * expose that in User-API endpoint
> 
>     * extend invectio report result to consider user-api endpoint and make results more robust? So we can use them in jupyterlab-requirements to discover Pipfile from notebook without dependencies and kebechet manager ([Uninstall unused libraries kebechet#727](https://github.com/thoth-station/kebechet/issues/727))?

Sounds good. Sure will do.
Thanks @fridex and @pacospace for input!

**Comment by fridex** [comment]
> * extend invectio report result to consider user-api endpoint and make results more robust? (@fridex) So we can use them in jupyterlab-requirements to discover Pipfile from notebook without dependencies and kebechet manager ([Uninstall unused libraries kebechet#727](https://github.com/thoth-station/kebechet/issues/727))? maybe an option, `--use-thoth`, not to consider the endpoint by default?

This might be better to have as a library function in thamos that talks to user-api.

**Comment by pacospace** [comment]
> > * extend invectio report result to consider user-api endpoint and make results more robust? (@fridex) So we can use them in jupyterlab-requirements to discover Pipfile from notebook without dependencies and kebechet manager ([Uninstall unused libraries kebechet#727](https://github.com/thoth-station/kebechet/issues/727))? maybe an option, `--use-thoth`, not to consider the endpoint by default?
> 
> This might be better to have as a library function in thamos that talks to user-api.

Right!! Thanks @fridex :)

**Review by pacospace — APPROVED** [review]
lgtm!! Thanks!

**Comment by tlegen-k** [comment]
> lgtm!! Thanks!

Thank you! My pleasure)

**Pull request merged**
