### PR TITLE
Instructions for accessing Thoth's public database on opf-datacatalog

### PR DESCRIPTION
**Pull request by mayaCostantini**
## Related Issues and Dependencies

Related to https://github.com/thoth-station/datasets/issues/32

## This introduces a breaking change

- [x] No

## This Pull Request implements

Instructions in docs to access the public Thoth database that will be published on `opf-datacatalog`.

### CODE REVIEW

**Comment by mayaCostantini** [comment]
/hold 
Waiting for database review and publication

**Review by fridex — COMMENTED** [review]
it might be worth stating the script introduced in https://github.com/thoth-station/datasets/pull/68 - it exists and we can use it to generate the dump (just to be aware of it)

Otherwise thanks! Looks good to me 👍🏻 💯

**Comment by mayaCostantini** [comment]
> it might be worth stating the script introduced in #68 

Right, thank you! :100:

**Pull request merged**
