### PR TITLE
Update/Add notebooks and datasets

### PR DESCRIPTION
**Pull request by pacospace**
Signed-off-by: Francesco Murdaca <fmurdaca@redhat.com>

## Related Issues and Dependencies

Fixes: https://github.com/thoth-station/datasets/issues/14

Fixes: https://github.com/thoth-station/notebooks/issues/70

## This introduces a breaking change

- [ ] Yes
- [x] No

## This Pull Request implements

- Migrate notebooks to use thoth-report-processing
- Introduce notebook to evaluate DM analysis for https://github.com/thoth-station/notebooks/issues/70
- Update README

### CODE REVIEW

**Review by fridex — APPROVED** [review]
:1st_place_medal: :1st_place_medal: :+1:

**Comment by pacospace** [comment]
no merging @goern @harshad16

**Comment by goern** [comment]
uhhh.. the check context has been renamed from `thoth-ci` to `aicoe-ci` ... I'll fix it

**Pull request merged**
